steps:
  - name: 'maven:3.6-jdk-11'  # Use a Maven Docker image to run the build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        mvn clean package
        cp -R Container1/target /workspace  # Copy artifacts to the workspace directory

  - name: 'gcr.io/cloud-builders/docker'  # Use the Docker builder image to build the Docker image
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/cloud-428816/k8s/container1:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'  # Push the Docker image to the Artifact Registry
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/cloud-428816/k8s/container1:latest'

images:
  - 'us-central1-docker.pkg.dev/cloud-428816/k8s/container1:latest'

substitutions:
  _GCP_PROJECT: 'cloud-428816'
  _GKE_CLUSTER: 'k8s-assignment'
  _GKE_ZONE: 'us-central1-c'
  _KUBERNETES_NAMESPACE: 'default'
  _ARTIFACT_REGISTRY: 'us-central1-docker.pkg.dev/cloud-428816/k8s'