# Global options for the build
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'maven:3.8.6-openjdk-17'
    entrypoint: 'mvn'
    args: [ 'clean', 'package', '-DskipTests' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'cloud-428816/k8s/container1:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'cloud-428816/k8s/container1:latest']

images:
  - 'cloud-428816/k8s/container1:latest'
